name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -c "from app.main import app; print('✅ App imports successfully')"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ secrets.SERVICE_NAME }}
        region: ${{ secrets.GCP_REGION }}
        source: .
        flags: |
          --allow-unauthenticated
          --port=8080
          --service-account=github-actions@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
          --set-env-vars=ENVIRONMENT=production
        
    - name: Get Service URL
      run: |
        SERVICE_URL=$(gcloud run services describe ${{ secrets.SERVICE_NAME }} --region=${{ secrets.GCP_REGION }} --format="value(status.url)")
        echo "🚀 Service deployed at: $SERVICE_URL"
